name: 🚀 Deploy to DO Droplet - Prod

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on Droplet
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DO_SSH_KEY }}

    - name: Deploy over SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
          set -e
          cd ~/apps/fastpaste
          if [ ! -d .git ]; then
            git clone https://github.com/${{ github.repository }} . || exit 1
          else
            git pull origin main || exit 1
          fi
          docker-compose down
          docker-compose up --build -d
        EOF
